name: fastq-peek functional test  # Name of the workflow

on:
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  verify-fqp-output:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make script executable
        run: chmod +x ./bin/fastq-peek.sh

      - name: Run fastq-peek script (Basic Test - No GC Content)
        id: run_script
        run: ./bin/fastq-peek.sh ./data/sample.fastq > actual_output.txt

      - name: Verify output (Basic Test)
        run: |
          echo "Processing FASTQ file: ./data/sample.fastq" > expected_output.txt
          echo "Number of reads in ./data/sample.fastq: 2" >> expected_output.txt
          
          echo "Expected Output:"
          cat expected_output.txt
          echo "Actual Output:"
          cat actual_output.txt

          if ! diff -q expected_output.txt actual_output.txt; then
            echo "Output did not match expected result."
            diff expected_output.txt actual_output.txt
            exit 1
          fi

      - name: Run fastq-peek script (With GC Content)
        id: run_script_gc
        run: ./bin/fastq-peek.sh --gc-content ./data/sample.fastq > actual_output_gc.txt

      - name: Verify output (With GC Content)
        run: |
          echo "Processing FASTQ file: ./data/sample.fastq" > expected_output_gc.txt
          echo "Number of reads in ./data/sample.fastq: 2" >> expected_output_gc.txt
          echo "GC content in ./data/sample.fastq: 50%" >> expected_output_gc.txt
          
          echo "Expected Output (With GC):"
          cat expected_output_gc.txt
          echo "Actual Output (With GC):"
          cat actual_output_gc.txt

          if ! diff -q expected_output_gc.txt actual_output_gc.txt; then
            echo "Output did not match expected result."
            diff expected_output_gc.txt actual_output_gc.txt
            exit 1
          fi

